# agenda
1. pandas can work as SQL, equivalent
2. pandas data structure.

# import package

In [28]:
import pandas as pd

# SQL equivalent

## read csv

In [37]:
url = '/content/drive/MyDrive/Colab Notebooks/tutorial_pandas/data.csv'
data = pd.read_csv(url)
data.head()

date  security_id  ...  TOTAL_ASSETS  WEEKLY_MOMENTUM
0  1990-03-01      1996480  ...  2.147045e+09         0.070428
1  1990-12-07      1989065  ...  7.637663e+10         0.064019
2  1991-03-01      1996480  ...  2.450408e+09         0.042240
3  1991-03-01      1988064  ...  3.646493e+10        -0.029487
4  1991-12-04      1989065  ...  7.710648e+10        -0.002160

[5 rows x 7 columns]

In [39]:
url = '/content/drive/MyDrive/Colab Notebooks/tutorial_pandas/dim.csv'
dim = pd.read_csv(url)
dim.head()

company_id  type
0     1996480     1
1     1989065     1
2     1988064     1
3     1976320     1
4     1969036     1

## select

```select * from table```

In [4]:
data

date  security_id  ...  TOTAL_ASSETS  WEEKLY_MOMENTUM
0     1990-03-01      1996480  ...  2.147045e+09         0.070428
1     1990-12-07      1989065  ...  7.637663e+10         0.064019
2     1991-03-01      1996480  ...  2.450408e+09         0.042240
3     1991-03-01      1988064  ...  3.646493e+10        -0.029487
4     1991-12-04      1989065  ...  7.710648e+10        -0.002160
...          ...          ...  ...           ...              ...
1405  2021-04-02      1990267  ...  1.310492e+11         0.029776
1406  2021-04-15      1990831  ...  5.965247e+09              NaN
1407  2021-04-16      1970786  ...  1.849663e+06              NaN
1408  2021-04-27      2009941  ...  1.799595e+07              NaN
1409  2021-05-03      2047725  ...  5.027968e+07              NaN

[1410 rows x 7 columns]

```select .... from table```

In [5]:
data[['date', 'security_id']]

date  security_id
0     1990-03-01      1996480
1     1990-12-07      1989065
2     1991-03-01      1996480
3     1991-03-01      1988064
4     1991-12-04      1989065
...          ...          ...
1405  2021-04-02      1990267
1406  2021-04-15      1990831
1407  2021-04-16      1970786
1408  2021-04-27      2009941
1409  2021-05-03      2047725

[1410 rows x 2 columns]

## limit

```select * from table limit n```

In [6]:
data[:5]

date  security_id  ...  TOTAL_ASSETS  WEEKLY_MOMENTUM
0  1990-03-01      1996480  ...  2.147045e+09         0.070428
1  1990-12-07      1989065  ...  7.637663e+10         0.064019
2  1991-03-01      1996480  ...  2.450408e+09         0.042240
3  1991-03-01      1988064  ...  3.646493e+10        -0.029487
4  1991-12-04      1989065  ...  7.710648e+10        -0.002160

[5 rows x 7 columns]

In [7]:
data.head(5)

date  security_id  ...  TOTAL_ASSETS  WEEKLY_MOMENTUM
0  1990-03-01      1996480  ...  2.147045e+09         0.070428
1  1990-12-07      1989065  ...  7.637663e+10         0.064019
2  1991-03-01      1996480  ...  2.450408e+09         0.042240
3  1991-03-01      1988064  ...  3.646493e+10        -0.029487
4  1991-12-04      1989065  ...  7.710648e+10        -0.002160

[5 rows x 7 columns]

```select * from table order by SALES desc limit 5```

In [24]:
data.nlargest(5, columns='SALES')

date  security_id  ...  TOTAL_ASSETS  WEEKLY_MOMENTUM
784  2012-03-15      1972156  ...  3.452570e+11        -0.010334
845  2013-03-14      1972156  ...  3.603250e+11        -0.000476
605  2009-03-17      1972156  ...  2.824010e+11         0.038183
907  2014-03-13      1972156  ...  3.575120e+11        -0.015087
974  2015-03-12      1972156  ...  3.531160e+11        -0.063880

[5 rows x 7 columns]

## where
```select * from table where condition1 ```

In [8]:
data[data.security_id == 1996480]

date  security_id  ...  TOTAL_ASSETS  WEEKLY_MOMENTUM
0     1990-03-01      1996480  ...  2.147045e+09         0.070428
2     1991-03-01      1996480  ...  2.450408e+09         0.042240
8     1993-03-01      1996480  ...  2.060528e+09        -0.066565
19    1994-03-01      1996480  ...  2.216529e+09         0.034841
35    1995-03-01      1996480  ...  2.487765e+09        -0.015892
52    1996-02-29      1996480  ...  3.283832e+09         0.025784
72    1997-03-01      1996480  ...  3.103499e+09        -0.020674
101   1998-03-01      1996480  ...  4.346577e+09         0.021000
130   1999-03-01      1996480  ...  4.502241e+09         0.009657
160   2000-02-25      1996480  ...  6.170213e+09        -0.007371
193   2001-02-23      1996480  ...  6.197930e+09        -0.032078
245   2002-04-10      1996480  ...  6.215065e+09        -0.029583
288   2003-04-07      1996480  ...  5.631241e+09         0.077027
312   2004-02-02      1996480  ...  6.203687e+09        -0.082939
368   2005-03-01      1996480  ...  6.881567e+09         0.022026
420   2006-03-01      1996480  ...  6.916494e+09        -0.003790
469   2007-02-20      1996480  ...  7.835810e+09         0.033663
546   2008-03-25      1996480  ...  9.396965e+09         0.014689
607   2009-03-26      1996480  ...  9.419070e+09         0.006140
663   2010-03-26      1996480  ...  9.344660e+09         0.009750
710   2011-03-15      1996480  ...  1.118762e+10        -0.060998
788   2012-03-19      1996480  ...  1.119017e+10         0.041697
852   2013-03-19      1996480  ...  1.255063e+10        -0.047654
906   2014-03-13      1996480  ...  1.381997e+10        -0.038584
973   2015-03-12      1996480  ...  1.223219e+10        -0.026364
1035  2016-03-10      1996480  ...  1.228276e+10         0.001817
1104  2017-03-10      1996480  ...  1.287347e+10        -0.008771
1170  2018-03-08      1996480  ...  1.520902e+10         0.015459
1240  2019-03-08      1996480  ...  1.025184e+10        -0.063807
1310  2020-03-06      1996480  ...  1.191835e+10        -0.024337
1387  2021-03-11      1996480  ...  1.343408e+10         0.060934

[31 rows x 7 columns]

```select * from table where condition1 and condition2```

In [9]:
data[(data.security_id == 1996480) & (data.date > '2000-01-01')]

date  security_id  ...  TOTAL_ASSETS  WEEKLY_MOMENTUM
160   2000-02-25      1996480  ...  6.170213e+09        -0.007371
193   2001-02-23      1996480  ...  6.197930e+09        -0.032078
245   2002-04-10      1996480  ...  6.215065e+09        -0.029583
288   2003-04-07      1996480  ...  5.631241e+09         0.077027
312   2004-02-02      1996480  ...  6.203687e+09        -0.082939
368   2005-03-01      1996480  ...  6.881567e+09         0.022026
420   2006-03-01      1996480  ...  6.916494e+09        -0.003790
469   2007-02-20      1996480  ...  7.835810e+09         0.033663
546   2008-03-25      1996480  ...  9.396965e+09         0.014689
607   2009-03-26      1996480  ...  9.419070e+09         0.006140
663   2010-03-26      1996480  ...  9.344660e+09         0.009750
710   2011-03-15      1996480  ...  1.118762e+10        -0.060998
788   2012-03-19      1996480  ...  1.119017e+10         0.041697
852   2013-03-19      1996480  ...  1.255063e+10        -0.047654
906   2014-03-13      1996480  ...  1.381997e+10        -0.038584
973   2015-03-12      1996480  ...  1.223219e+10        -0.026364
1035  2016-03-10      1996480  ...  1.228276e+10         0.001817
1104  2017-03-10      1996480  ...  1.287347e+10        -0.008771
1170  2018-03-08      1996480  ...  1.520902e+10         0.015459
1240  2019-03-08      1996480  ...  1.025184e+10        -0.063807
1310  2020-03-06      1996480  ...  1.191835e+10        -0.024337
1387  2021-03-11      1996480  ...  1.343408e+10         0.060934

[22 rows x 7 columns]

```select date, security_id from table where condition1 & condition2```

In [10]:
data[(data.security_id == 1996480) & (data.date > '2000-01-01')][['security_id', 'date']]

security_id        date
160       1996480  2000-02-25
193       1996480  2001-02-23
245       1996480  2002-04-10
288       1996480  2003-04-07
312       1996480  2004-02-02
368       1996480  2005-03-01
420       1996480  2006-03-01
469       1996480  2007-02-20
546       1996480  2008-03-25
607       1996480  2009-03-26
663       1996480  2010-03-26
710       1996480  2011-03-15
788       1996480  2012-03-19
852       1996480  2013-03-19
906       1996480  2014-03-13
973       1996480  2015-03-12
1035      1996480  2016-03-10
1104      1996480  2017-03-10
1170      1996480  2018-03-08
1240      1996480  2019-03-08
1310      1996480  2020-03-06
1387      1996480  2021-03-11

## aggregate 
mean, max, min

In [11]:
data.agg({'SALES': ['mean', 'max', 'min']})

SALES
mean  1.613002e+10
max   4.701710e+11
min  -2.600215e+08

```select security_id, count(*) from table group by security_id```

In [12]:
data['security_id'].value_counts()

1996480    31
1989065    30
1988064    30
1969036    29
1989464    29
           ..
1954107     1
2009037     1
1999533     1
1999422     1
2027457     1
Name: security_id, Length: 99, dtype: int64

## distinct
```select distinct security_id from table```

In [13]:
data['security_id'].unique()

array([1996480, 1989065, 1988064, 1976320, 1969036, 1988560, 1981117,
       1989464, 2048071, 1954739, 1967753, 1954065, 1969863, 1966585,
       1954245, 2008340, 1971519, 1954291, 1984920, 1996562, 2047493,
       1955280, 1957233, 1956162, 1988574, 1972156, 1954416, 1955072,
       1961774, 1954107, 1954165, 2021670, 1983365, 1958970, 2023908,
       1979229, 1995136, 1966258, 1988241, 1989527, 1975701, 1954929,
       1983879, 1997022, 1990267, 2000706, 1979646, 1970632, 1981391,
       1970005, 2017345, 1969831, 1971163, 1972326, 1993643, 2017766,
       1970170, 2047855, 1993347, 1972575, 1989944, 1990831, 1993499,
       1973022, 1992992, 1997175, 1992748, 1999422, 1998003, 1999809,
       2007253, 2008197, 2009037, 2009001, 2022956, 2011065, 2010016,
       2012821, 2010909, 1999533, 2022656, 2025205, 2018071, 2009941,
       1970786, 2021553, 2023918, 2026552, 2027457, 2040900, 2035494,
       2029180, 2027300, 2030716, 2032065, 2047725, 2035741, 2036844,
       2041539])

## order by
```select * from table where security_id = 1996480 order by date```

In [14]:
data[data.security_id == 1996480].sort_values('date', ascending=False)

date  security_id  ...  TOTAL_ASSETS  WEEKLY_MOMENTUM
1387  2021-03-11      1996480  ...  1.343408e+10         0.060934
1310  2020-03-06      1996480  ...  1.191835e+10        -0.024337
1240  2019-03-08      1996480  ...  1.025184e+10        -0.063807
1170  2018-03-08      1996480  ...  1.520902e+10         0.015459
1104  2017-03-10      1996480  ...  1.287347e+10        -0.008771
1035  2016-03-10      1996480  ...  1.228276e+10         0.001817
973   2015-03-12      1996480  ...  1.223219e+10        -0.026364
906   2014-03-13      1996480  ...  1.381997e+10        -0.038584
852   2013-03-19      1996480  ...  1.255063e+10        -0.047654
788   2012-03-19      1996480  ...  1.119017e+10         0.041697
710   2011-03-15      1996480  ...  1.118762e+10        -0.060998
663   2010-03-26      1996480  ...  9.344660e+09         0.009750
607   2009-03-26      1996480  ...  9.419070e+09         0.006140
546   2008-03-25      1996480  ...  9.396965e+09         0.014689
469   2007-02-20      1996480  ...  7.835810e+09         0.033663
420   2006-03-01      1996480  ...  6.916494e+09        -0.003790
368   2005-03-01      1996480  ...  6.881567e+09         0.022026
312   2004-02-02      1996480  ...  6.203687e+09        -0.082939
288   2003-04-07      1996480  ...  5.631241e+09         0.077027
245   2002-04-10      1996480  ...  6.215065e+09        -0.029583
193   2001-02-23      1996480  ...  6.197930e+09        -0.032078
160   2000-02-25      1996480  ...  6.170213e+09        -0.007371
130   1999-03-01      1996480  ...  4.502241e+09         0.009657
101   1998-03-01      1996480  ...  4.346577e+09         0.021000
72    1997-03-01      1996480  ...  3.103499e+09        -0.020674
52    1996-02-29      1996480  ...  3.283832e+09         0.025784
35    1995-03-01      1996480  ...  2.487765e+09        -0.015892
19    1994-03-01      1996480  ...  2.216529e+09         0.034841
8     1993-03-01      1996480  ...  2.060528e+09        -0.066565
2     1991-03-01      1996480  ...  2.450408e+09         0.042240
0     1990-03-01      1996480  ...  2.147045e+09         0.070428

[31 rows x 7 columns]

## group by
count

In [15]:
data.groupby(['security_id']).size().to_frame('count').reset_index()

security_id  count
0       1954065     27
1       1954107      1
2       1954165     24
3       1954245     27
4       1954291     26
..          ...    ...
94      2041539      2
95      2047493     24
96      2047725      5
97      2047855      8
98      2048071      6

[99 rows x 2 columns]

## having
```select security_id, count(*) as cnt from table group by security_id having cnt > 20```

In [26]:
data.groupby('security_id').filter(lambda x : len(x) > 10).groupby('security_id').size()

security_id
1954065    27
1954165    24
1954245    27
1954291    26
1954739    28
           ..
2010909    11
2017345    18
2022956    11
2023908    17
2047493    24
Length: 61, dtype: int64

## in

In [21]:
data[data.security_id.isin([1954065, 1954165])].head(5)

date  security_id  ...  TOTAL_ASSETS  WEEKLY_MOMENTUM
24  1994-04-28      1954065  ...           NaN         0.023256
40  1995-04-28      1954065  ...  4.079117e+07         0.033333
59  1996-05-23      1954065  ...  4.262131e+07         0.000000
87  1997-05-28      1954065  ...  4.599476e+07         0.000000
93  1997-12-31      1954165  ...  5.006000e+09              NaN

[5 rows x 7 columns]

## not in

In [23]:
data[~data.security_id.isin([1954065, 1954165])].head(5)

date  security_id  ...  TOTAL_ASSETS  WEEKLY_MOMENTUM
0  1990-03-01      1996480  ...  2.147045e+09         0.070428
1  1990-12-07      1989065  ...  7.637663e+10         0.064019
2  1991-03-01      1996480  ...  2.450408e+09         0.042240
3  1991-03-01      1988064  ...  3.646493e+10        -0.029487
4  1991-12-04      1989065  ...  7.710648e+10        -0.002160

[5 rows x 7 columns]

## union
```select * from table where date < '2000-01-01' union all select * from talbe where date > '2010-01-01'```

In [25]:
pd.concat([data[data.date < '2000-01-01'], data[data.date > '2010-01-01']])

date  security_id  ...  TOTAL_ASSETS  WEEKLY_MOMENTUM
0     1990-03-01      1996480  ...  2.147045e+09         0.070428
1     1990-12-07      1989065  ...  7.637663e+10         0.064019
2     1991-03-01      1996480  ...  2.450408e+09         0.042240
3     1991-03-01      1988064  ...  3.646493e+10        -0.029487
4     1991-12-04      1989065  ...  7.710648e+10        -0.002160
...          ...          ...  ...           ...              ...
1405  2021-04-02      1990267  ...  1.310492e+11         0.029776
1406  2021-04-15      1990831  ...  5.965247e+09              NaN
1407  2021-04-16      1970786  ...  1.849663e+06              NaN
1408  2021-04-27      2009941  ...  1.799595e+07              NaN
1409  2021-05-03      2047725  ...  5.027968e+07              NaN

[932 rows x 7 columns]

## join
```select * from table join dim on table.security_id = dim.company_id where table.security_id = 1954065```

In [40]:
data.merge(dim[data.security_id == 1954065], left_on='security_id', right_on='company_id', how='inner')

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.


date  security_id  12M_MOMENTUM  ...  WEEKLY_MOMENTUM  company_id  type
0   1997-02-28      1988574     -0.166939  ...        -0.005443     1988574     1
1   1998-02-28      1988574     -0.325586  ...         0.000189     1988574     1
2   1999-05-20      1988574      0.159009  ...         0.020217     1988574     1
3   2000-02-29      1988574      0.047865  ...        -0.041494     1988574     1
4   2001-02-28      1988574      0.134812  ...         0.015572     1988574     1
5   2002-03-01      1988574     -0.097919  ...        -0.008252     1988574     1
6   2003-06-30      1988574      0.180859  ...        -0.004135     1988574     1
7   2004-03-30      1988574      0.137232  ...        -0.016822     1988574     1
8   2010-04-26      1988574           NaN  ...        -0.009339     1988574     1
9   2011-05-30      1988574      0.162324  ...         0.018702     1988574     1
10  2012-04-20      1988574     -0.093690  ...         0.010571     1988574     1
11  2013-05-09      1988574     -0.262668  ...         0.004060     1988574     1
12  2014-05-05      1988574     -0.434224  ...         0.002359     1988574     1
13  2015-06-19      1988574     -0.168279  ...         0.005212     1988574     1
14  2016-04-25      1988574      0.136256  ...        -0.003946     1988574     1
15  2017-05-10      1988574     -0.034611  ...        -0.002716     1988574     1
16  2018-04-30      1988574      0.217009  ...        -0.010747     1988574     1
17  2019-05-03      1988574     -0.156123  ...         0.004591     1988574     1
18  2020-05-29      1988574     -0.219778  ...         0.017641     1988574     1

[19 rows x 9 columns]

## rename the column
```to_frame()```

In [ ]:
data.groupby(['security_id']).size().to_frame('count')

## reset the index

In [19]:
data.groupby(['security_id']).size().reset_index()

security_id   0
0       1954065  27
1       1954107   1
2       1954165  24
3       1954245  27
4       1954291  26
..          ...  ..
94      2041539   2
95      2047493  24
96      2047725   5
97      2047855   8
98      2048071   6

[99 rows x 2 columns]

## insert

In [41]:
dim = dim.append({'company_id': 118, 'type': 9}, ignore_index=True)
dim

company_id  type
0      1996480     1
1      1989065     1
2      1988064     1
3      1976320     1
4      1969036     1
5      1988560     1
6      1981117     1
7      1989464     1
8      2048071     1
9      1954739     1
10     1967753     1
11     1954065     1
12     1969863     1
13     1966585     1
14     1954245     1
15     2008340     1
16     1971519     1
17     1954291     1
18     1984920     1
19     1996562     1
20     2047493     1
21     1955280     1
22     1957233     1
23     1956162     1
24     1988574     1
25     1972156     1
26     1954416     1
27     1955072     1
28     1961774     1
29     1954107     1
30     1954165     1
31         118     9

# update

In [43]:
dim.loc[dim.company_id == 118, 'type'] = 2
dim

company_id  type
0      1996480     1
1      1989065     1
2      1988064     1
3      1976320     1
4      1969036     1
5      1988560     1
6      1981117     1
7      1989464     1
8      2048071     1
9      1954739     1
10     1967753     1
11     1954065     1
12     1969863     1
13     1966585     1
14     1954245     1
15     2008340     1
16     1971519     1
17     1954291     1
18     1984920     1
19     1996562     1
20     2047493     1
21     1955280     1
22     1957233     1
23     1956162     1
24     1988574     1
25     1972156     1
26     1954416     1
27     1955072     1
28     1961774     1
29     1954107     1
30     1954165     1
31         118     2

## delete

In [45]:
dim = dim.drop(dim[dim.type==2].index)
dim

company_id  type
0      1996480     1
1      1989065     1
2      1988064     1
3      1976320     1
4      1969036     1
5      1988560     1
6      1981117     1
7      1989464     1
8      2048071     1
9      1954739     1
10     1967753     1
11     1954065     1
12     1969863     1
13     1966585     1
14     1954245     1
15     2008340     1
16     1971519     1
17     1954291     1
18     1984920     1
19     1996562     1
20     2047493     1
21     1955280     1
22     1957233     1
23     1956162     1
24     1988574     1
25     1972156     1
26     1954416     1
27     1955072     1
28     1961774     1
29     1954107     1
30     1954165     1